// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdmzylggisbudnddcpfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkbXp5bGdnaXNidWRuZGRjcGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Nzg2OTYsImV4cCI6MjA1OTM1NDY5Nn0.IBw-F_-mAZIuhClAB6RtFp34czJcAQWOXXfhZj0RMzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storageKey: 'learnverse-web-auth',
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Public client for anonymous access
export const publicSupabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storageKey: 'learnverse-web-public',
      persistSession: false,
      autoRefreshToken: false,
    },
    global: {
      headers: {
        'x-client-info': 'public-access',
      },
    },
  }
);

// One-time function to update college_content bucket size limit
export async function updateCollegeContentBucketSizeLimit() {
  try {
    const { error } = await supabase.storage.updateBucket('college_content', {
      fileSizeLimit: 2 * 1024 * 1024 * 1024 // 2GB
    });
    
    if (error) {
      console.error('Error updating college_content bucket size limit:', error);
      return false;
    }
    
    console.log('Successfully updated college_content bucket size limit to 2GB');
    return true;
  } catch (error) {
    console.error('Error updating college_content bucket size limit:', error);
    return false;
  }
}